version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: /Users/prudhviraj/Documents/finance/Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 finance.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: awspostgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
